"""Initial schema: missions, phases, risks

Revision ID: e070a5d26379
Revises: 
Create Date: 2026-06-25 23:30:43.710315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e070a5d26379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('this_week', sa.String(), nullable=True),
    sa.Column('today_focus', sa.String(), nullable=True),
    sa.Column('exit_gate', sa.String(), nullable=True),
    sa.Column('ai_stage', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_id'), ['id'], unique=False)

    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('weeks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phases_phase_num'), ['phase_num'], unique=True)

    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('probability', sa.String(), nullable=False),
    sa.Column('mitigation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_id'))

    op.drop_table('risks')
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phases_phase_num'))
        batch_op.drop_index(batch_op.f('ix_phases_id'))

    op.drop_table('phases')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_id'))

    op.drop_table('missions')
    # ### end Alembic commands ###
